name: fire_app
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.27.3
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: null
  animator: null
  bloc: ^9.0.0
  cached_network_image: null
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dartz: null
  dio: null
  easy_localization: null
  equatable: null
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_animate: null
  flutter_bloc: ^9.1.1
  # flutter_firebase_auth_repository: ^1.0.2
  flutter_launcher_icons: null
  flutter_native_splash: null
  flutter_screenutil: null
  flutter_svg: null
  get_it: null
  google_fonts: null
  google_sign_in: 7.1.1
  intl: null
  json_annotation: null
  lottie: null
  shared_preferences: null
  awesome_dialog: ^3.1.0

dev_dependencies:
  bloc_test: null
  build_runner: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  # freezed: null
  json_serializable: null
  mockito: null

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
